import type { CardData } from './types';

/**
 * エンシェントから授かるカード（キャラクター固有カードは除く）。
 * リージェント専用カード・無色カードとは別に管理する。
 * 出典: https://wikiwiki.jp/sts2/%E5%85%A8%E3%82%AF%E3%83%A9%E3%82%B9%E5%85%B1%E9%80%9A%28%E3%82%A2%E3%83%BC%E3%83%AA%E3%83%BC%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%29
 * rarityフィールドには付与元のエンシェント名を格納する。
 */
export const ANCIENT_CARDS: CardData[] = [
  {
    id: 'ancient-attack-01',
    name: 'ネオーの怒り',
    type: 'attack',
    rarity: 'ネオー',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 10,
    plusValue: 14,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '10ダメージを与える。捨て札から最大2枚のカードを手札に加える。廃棄。',
    effectPlus: '14ダメージを与える。捨て札から最大3枚のカードを手札に加える。廃棄。',
  },
  {
    id: 'ancient-attack-02',
    name: '引き裂き',
    type: 'attack',
    rarity: 'タンクス',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 10,
    plusValue: 12,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '5ダメージを2回与える。この戦闘中、すべての引き裂きのダメージが1増加する。',
    effectPlus: '6ダメージを2回与える。この戦闘中、すべての引き裂きのダメージが2増加する。',
  },
  {
    id: 'ancient-attack-03',
    name: 'ホイッスル',
    type: 'attack',
    rarity: 'タンクス',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 33,
    plusValue: 44,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '33ダメージを与える。この敵をスタンさせる。廃棄。',
    effectPlus: '44ダメージを与える。この敵をスタンさせる。廃棄。',
  },
  {
    id: 'ancient-skill-01',
    name: '願い',
    type: 'skill',
    rarity: 'ヴァクー',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札からカードを1枚手札に加える。廃棄。',
    effectPlus: '保留。山札からカードを1枚手札に加える。廃棄。',
  },
  {
    id: 'ancient-skill-02',
    name: '極光の炎',
    type: 'skill',
    rarity: 'テスカタラ',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '●●を得る。カードを2枚引く。最大HPを1失う。',
    effectPlus: '●●●を得る。カードを3枚引く。最大HPを1失う。',
  },
  {
    id: 'ancient-skill-03',
    name: '幻姿',
    type: 'skill',
    rarity: 'ヴァクー',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'エセリアル。霊体1を得る。廃棄。',
    effectPlus: '霊体1を得る。廃棄。',
  },
  {
    id: 'ancient-skill-04',
    name: '神格化',
    type: 'skill',
    rarity: 'ノヌペイペ',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '天賦。すべてのカードをアップグレードする。廃棄。',
    effectPlus: '天賦。すべてのカードをアップグレードする。廃棄。',
  },
  {
    id: 'ancient-skill-05',
    name: 'リラックス',
    type: 'skill',
    rarity: 'パエル',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 15,
    plusValue: 17,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '15ブロックを得る。次のターン、カードを2枚引き、●●を得る。廃棄。',
    effectPlus: '17ブロックを得る。次のターン、カードを3枚引き、●●●を得る。廃棄。',
  },
];
